//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDZ.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class IDZ_view
    {
        public string serviceName { get; set; }
        public Nullable<int> averageExecutionTimeInMinutes { get; set; }
        public Nullable<int> numberOfMasters { get; set; }
    }
}
