//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDZ.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class providedService
    {
        public System.Guid providedServiceID { get; set; }
        public System.DateTime providedServiceDateTime { get; set; }
        public string providedServiceStatus { get; set; }
        public System.Guid clientID { get; set; }
        public System.Guid masterID { get; set; }
        public string serviceName { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Masters_Services Masters_Services { get; set; }
    }
}
